on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install poetry
      - run: poetry install
      - name: Log into Dockerhub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: assaflavie
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - run: make test
      - if: ${{ failure() }}
        run: ./inspect_fixtures.sh
