on:
  push:
    branches: ["master"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install poetry
      - run: poetry install
      - run: make pypi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      - run: bin/wait_for_pip.sh $(poetry run ./current_version.py)
      - name: Log into Dockerhub
        uses: docker/login-action@v2
        with:
          username: assaflavie
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make push
